default:
    @just --list

run DAY PART:
    elixir "./day{{DAY}}/{{DAY}}-{{PART}}.exs"

new DAY:
    mkdir day{{DAY}}
    touch "day{{DAY}}/data.txt"
    cp "template.exs" "day{{DAY}}/{{DAY}}-1.exs"
    cp "template.exs" "day{{DAY}}/{{DAY}}-2.exs"

    sd -F "[[DAY]]" "{{DAY}}" "day{{DAY}}/{{DAY}}-1.exs"
    sd -F "[[PART]]" "1" "day{{DAY}}/{{DAY}}-1.exs"

    sd -F "[[DAY]]" "{{DAY}}" "day{{DAY}}/{{DAY}}-2.exs"
    sd -F "[[PART]]" "2" "day{{DAY}}/{{DAY}}-2.exs"
